# Generated by Django 5.2.8 on 2025-11-11 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(default='none', max_length=50, unique=True, verbose_name='닉네임')),
                ('role', models.CharField(choices=[('GENERAL', '일반 회원'), ('ADMIN', '운영자'), ('MANAGER', '총관리자')], default='GENERAL', max_length=50, verbose_name='사용자 역할')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모임 이름')),
                ('category', models.CharField(choices=[('SPORTS', '체육'), ('ART', '미술'), ('MUSIC', '음악'), ('COOKING', '요리/베이커리'), ('READING', '독서'), ('OTHER', '기타')], max_length=50, verbose_name='카테고리')),
                ('region', models.CharField(max_length=50, verbose_name='활동 지역')),
                ('status', models.CharField(choices=[('RECRUITING', '모집 중'), ('CLOSED', '모집 마감'), ('OPERATING', '운영 중')], default='RECRUITING', max_length=50, verbose_name='모임 상태')),
                ('description', models.TextField(verbose_name='모임 소개')),
                ('max_members', models.PositiveIntegerField(verbose_name='최대 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='개설자')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('description', models.CharField(max_length=255, verbose_name='내용')),
                ('transaction_date', models.DateField(auto_now_add=True, verbose_name='거래 날짜')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to=settings.AUTH_USER_MODEL, verbose_name='관련 사용자 (납부자/지출 처리자)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='club_management.group')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='일정 제목')),
                ('date_time', models.DateTimeField(verbose_name='날짜 및 시간')),
                ('location', models.CharField(max_length=255, verbose_name='장소')),
                ('content', models.TextField(verbose_name='활동 내용')),
                ('participation_fee', models.PositiveIntegerField(default=0, help_text='이 일정에 참여하는 멤버가 납부해야 할 금액', verbose_name='참가 회비')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='club_management.group')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('LEADER', '리더'), ('ADMIN', '총무/운영진'), ('MEMBER', '일반 회원'), ('PENDING', '가입 대기 중')], default='PENDING', max_length=50, verbose_name='멤버 역할/권한')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '모임 멤버',
                'verbose_name_plural': '모임 멤버 목록',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('ATTENDING', '참석'), ('NOT_ATTENDING', '불참'), ('PENDING', '미정/미응답'), ('PRESENT', '출석 (운영진 체크)'), ('ABSENT', '결석 (운영진 체크)')], default='PENDING', max_length=50, verbose_name='참석/출석 상태')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='응답 시각')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.activityschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일정 참석 응답/출석',
                'verbose_name_plural': '일정 참석 응답/출석 목록',
                'unique_together': {('user', 'schedule')},
            },
        ),
    ]
