# Generated by Django 5.2.8 on 2025-11-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='모임 이름')),
                ('region', models.CharField(max_length=50, verbose_name='활동 지역')),
                ('description', models.TextField(verbose_name='모임 소개')),
                ('is_active', models.BooleanField(default=True, verbose_name='활동 중 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_management.category', verbose_name='카테고리')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clubs', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '모임',
                'verbose_name_plural': '모임 목록',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', '리더 (모임 생성자/최고 관리자)'), ('MANAGER', '총무/운영진'), ('MEMBER', '일반 멤버')], default='MEMBER', max_length=10, verbose_name='역할')),
                ('status', models.CharField(choices=[('PENDING', '가입 신청 대기'), ('APPROVED', '승인 완료'), ('REJECTED', '거절됨')], default='PENDING', max_length=10, verbose_name='가입 상태')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club', verbose_name='모임')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '모임 멤버',
                'verbose_name_plural': '모임 멤버 관리',
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='일정 제목')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='장소')),
                ('description', models.TextField(blank=True, verbose_name='세부 내용')),
                ('required_fee', models.IntegerField(default=0, verbose_name='참석 시 회비(선택)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club', verbose_name='모임')),
            ],
            options={
                'verbose_name': '모임 일정',
                'verbose_name_plural': '일정 관리',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('INCOME', '수입 (회비, 지원금 등)'), ('EXPENSE', '지출 (장소, 재료비 등)')], max_length=10, verbose_name='구분')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('description', models.CharField(max_length=255, verbose_name='내역')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club', verbose_name='모임')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='기록자')),
            ],
            options={
                'verbose_name': '재정 기록',
                'verbose_name_plural': '재정 장부',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('ATTEND', '참석 예정'), ('ABSENT', '불참'), ('MAYBE', '미정')], default='MAYBE', max_length=10, verbose_name='사전 참석 응답')),
                ('actual_status', models.CharField(choices=[('PRESENT', '출석'), ('ABSENT', '결석'), ('NOT_CHECKED', '미확인')], default='NOT_CHECKED', max_length=15, verbose_name='실제 출석 여부')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='출석 체크 시간')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_checker', to=settings.AUTH_USER_MODEL, verbose_name='출석 체크 담당자')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.clubmember', verbose_name='모임 멤버')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.event', verbose_name='일정')),
            ],
            options={
                'verbose_name': '출석/참석 기록',
                'verbose_name_plural': '출석 기록',
                'unique_together': {('event', 'member')},
            },
        ),
    ]
