# Generated by Django 5.2.6 on 2025-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0002_boardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('GYEONGGI', '경기'), ('INCHEON', '인천'), ('ETC', '기타/온라인')], default='SEOUL', max_length=20, verbose_name='선호 활동 지역'),
        ),
    ]
